- name: create AD
  hosts: dc01
  vars_prompt:
      - name: admin_password
        prompt: Set the password
        update_password: always
  tasks:
    - name: Set hostname
      windows_hostname:
        name: "{{ hostname }}"
      register: reboothostname
    - name: Reboot hostname
      ansible.windows.win_reboot:
      when: reboothostname.reboot.required

    - name: Create new forest
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_password }}"
        safe_mode_password: "{{safe_mode_password }}"
        install_dns: yes
        restart: yes
        register: rebootDomain
    - name: Reboot Domain 
      ansible.windows.win_reboot:
      when: rebootDomain.reboot_required

    - name: Create OU structure in Active Directory
      win_domain_hierarchy:
        object: ou=Test,{{ ldap_base_dn }}
        children:
          - ou=OU1,ou=Test,{{ ldap_base_dn }}

